on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: windows-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with: 
              dotnet-version: 5.0
        - name: Add msbuild to PATH
          uses: microsoft/setup-msbuild@v1.1
        - name: Build app for release
          run: msbuild 'DU Market API/DU Market API.vbproj' -t:rebuild -verbosity:diag -property:Configuration=Release
        - name: Create github Release
          id: create_release
          uses: actions/create-release@v1
          env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
              tag_name: v1.61.3
              release_name: 'DUOpenMarket v1.61.4'
              draft: false
              prerelease: false
        - name: Remove old release
          uses: dev-drprasad/delete-tag-and-release@v0.2.0
          with: 
              delete_release: true
              tag_name: Auto-build
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Upload release
          uses: actions/upload-release-asset@v1
          env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: "./DU Market API/bin/Release/app.publish/DUOpenMarket Client.exe"
              asset_name: "DUOpenMarket Client.exe"
              asset_content_type: application/zip
        - name: Publish release
          uses: eregon/publish-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release_id: ${{ steps.create_release.outputs.id }}
